### ISSUE TITLE
学マスのアイドルの色を追加したい

### ISSUE THREAD

**Issue by banjun** [imas/imasparql#557]
#552 で花海咲季の色が追加されているので、それに習って色を追加したい

| 学園名簿 | 楽曲配信開始ニュース(参考) | 学園名簿のURL |
| ---- | ---- | ---- |
| `#EA4A5B` | `#e2041b` | https://gakuen.idolmaster-official.jp/assets/img/idol/saki/thumb.png |
| `#4FA0CE` | `#007bbb` | https://gakuen.idolmaster-official.jp/assets/img/idol/temari/thumb.png |
| `#FAD356` | `#f7c114` | https://gakuen.idolmaster-official.jp/assets/img/idol/kotone/thumb.png |
| `#A453A6` | `#7f1184` | https://gakuen.idolmaster-official.jp/assets/img/idol/mao/thumb.png |
| `#EFFDFF` | `#eafdff` | https://gakuen.idolmaster-official.jp/assets/img/idol/lilja/thumb.png |
| `#F8AC5E` | `#f68b1f` | https://gakuen.idolmaster-official.jp/assets/img/idol/china/thumb.png |
| `#A2FD47` | `#7cfc00` | https://gakuen.idolmaster-official.jp/assets/img/idol/sumika/thumb.png |
| `#48C6DA` | `#00afcc` | https://gakuen.idolmaster-official.jp/assets/img/idol/hiro/thumb.png |
| `#F9C4D6` | `#f6adc6` | https://gakuen.idolmaster-official.jp/assets/img/idol/rinami/thumb.png |
| `#EF8472` | - | https://gakuen.idolmaster-official.jp/assets/img/idol/ume/thumb.png |
| `#A0B6DC` | - | https://gakuen.idolmaster-official.jp/assets/img/idol/misuzu/thumb.png |
| `#F9C584` | - | https://gakuen.idolmaster-official.jp/assets/img/idol/sena/thumb.png |
| `#A6E4C7` | - | https://gakuen.idolmaster-official.jp/assets/img/idol/asari/thumb.png |
| `#F6B549` | - | https://gakuen.idolmaster-official.jp/assets/img/idol/kunio/thumb.png |

参考情報として 【学マス】楽曲サブスク解禁開始記念！ 楽曲最新情報まとめNews ★インスト音源配布情報も！ ニュース記事にあるソロ曲の文字コードもカラムに入れました(白地に明るい文字がそのまま使われているので，色調整していない可能性あると思ったので)
https://idolmaster-official.jp/news/01_11523

https://github.com/imas/imasparql/assets/11156/b0a3e9bb-57fb-4f69-8c90-bf3b51819699

**Comment by banjun** [comment]
楽曲配信開始ニュース(参考)カラムをPR本文に追加

**Comment by suienzan** [comment]
![Saki Hanami](https://github.com/imas/imasparql/assets/23496542/83b14f42-0b52-4bd0-a58c-ef2535d6bd8e)
ここのテキストの背景は実際には単色です。その上に半透明のグラデーションレイヤーを重ねます。

ソースコードにはこうようなものがいる。

```CSS
.idol__serif.saki .idol__serif-text::before {
  background-color:#e30f25
}
.idol__serif.temari .idol__serif-text::before {
  background-color:#0c7bbb
}
.idol__serif.kotone .idol__serif-text::before {
  background-color:#f8c112
}
.idol__serif.rinami .idol__serif-text::before {
  background-color:#f6adc6
}
.idol__serif.sumika .idol__serif-text::before {
  background-color:#7cfc00
}
.idol__serif.hiro .idol__serif-text::before {
  background-color:#00afcc
}
.idol__serif.lilja .idol__serif-text::before {
  background-color:#eafdff
}
.idol__serif.china .idol__serif-text::before {
  background-color:#f68b1f
}
.idol__serif.mao .idol__serif-text::before {
  background-color:#7f1184
}
.idol__serif.ume .idol__serif-text::before {
  background-color:#ea533a
}
```
